name: Create AWS test infrastructure
on: 
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets[format('{0}_AWS_ACCESS_KEY_ID', github.triggering_actor)] }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets[format('{0}_AWS_SECRET_ACCESS_KEY', github.triggering_actor)] }}

jobs:
  create:
    name: Create resources
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.2
      - name: Terraform init
        id: init
        run: terraform init
        working-directory: ./terraform/aws
      - name: Terraform plan
        id: plan
        run: terraform plan -out=tfplan
        working-directory: ./terraform/aws
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ./terraform/aws

      - name: Upload Terraform state
        uses: actions/upload-artifact@v4
        with:
          name: terraform_state
          path: ./terraform/aws/terraform.tfstate